replicaCount: 1
clusterName: eshop-eks
pathBase: /
serviceAccountName: eshop-eks-sa

image:
  repository: eshop/webspa
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  class: aws-alb
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  # annotations: 
  #   alb.ingress.kubernetes.io/group.order: "10"
  #   alb.ingress.kubernetes.io/target-type: 'instance'
  #   alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30" # in seconds
  #   alb.ingress.kubernetes.io/healthcheck-path: /healhtz
  #   alb.ingress.kubernetes.io/healty-threshold-count: "1"
  #   # by default, it will create a listener rule on port 80
  #   # you can specify both ports as well like this: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  #   alb.ingress.kubernetes.io/scheme: internet-facing
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: DPConnectionString
      key: webspa__keystore
    - name: MarketingUrl
      key: urls__apigwwm
    - name: PurchaseUrl
      key: urls__apigwws
    - name: CallBackUrl
      key: urls__spa
    - name: IdentityUrl
      key: urls__IdentityUrl
    - name: IdentityUrlHC
      key: internalurls__identity__hc      
    - name: SignalrHubUrl
      key: urls__apigwws
    - name: Serilog__SeqServerUrl
      key: all__Serilog__SeqServerUrl
    - name: Serilog__LogstashgUrl
      key:  all__Serilog__LogstashgUrl
    - name: Serilog__LokiUrl
      key:  all__Serilog__LokiUrl
    - name: UseAWS
      key: all__UseAWS
    - name: UseVault
      key: all__UseVault
    - name: OtlpEndpoint
      key: all__OtlpEndpoint
    - name: LocalStack__UseLocalStack
      key: all__LocalStack__UseLocalStack
    - name: LocalStack__LocalStackUrl
      key: all__LocalStack__LocalStackUrl
    - name: AWS__Profile
      key: all__AWS__Profile
    - name: AWS__Region
      key: all__AWS__Region
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ActivateCampaignDetailFunction
      value: true
    - name: UseCustomizationData
      value: false
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: ASPNETCORE_URLS
      value: http://0.0.0.0:80
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'

