apiVersion: v1
kind: ServiceAccount
metadata:
  name: eshop-eks-sa
  namespace: default
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::791977570179:role/EshopEksForOidcSa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
- kind: ServiceAccount
  name: eshop-eks-sa
  namespace: default
