replicaCount: 1
clusterName: eshop-eks
pathBase: /webstatus
serviceAccountName: eshop-eks-sa

image:
  repository: eshop/webstatus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  class: aws-alb
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  # annotations: 
  #   alb.ingress.kubernetes.io/group.order: "10"
  #   alb.ingress.kubernetes.io/target-type: 'instance'
  #   alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30" # in seconds
  #   alb.ingress.kubernetes.io/healthcheck-path: /healhtz
  #   alb.ingress.kubernetes.io/healty-threshold-count: "1"
  #   # by default, it will create a listener rule on port 80
  #   # you can specify both ports as well like this: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  #   alb.ingress.kubernetes.io/scheme: internet-facing
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: HealthChecks-UI__HealthChecks__0__Name
      key: name__mvc__hc
    - name: HealthChecks-UI__HealthChecks__0__Uri
      key: internalurls__mvc__hc
    - name: HealthChecks-UI__HealthChecks__1__Name
      key: name__spa__hc
    - name: HealthChecks-UI__HealthChecks__1__Uri
      key: internalurls__spa__hc
    - name: HealthChecks-UI__HealthChecks__2__Name
      key: name__apigwwsagg__hc
    - name: HealthChecks-UI__HealthChecks__2__Uri
      key: internalurls__apigwwsagg__hc
    - name: HealthChecks-UI__HealthChecks__3__Name
      key: name__apigwmsagg__hc
    - name: HealthChecks-UI__HealthChecks__3__Uri
      key: internalurls__apigwmsagg__hc
    - name: HealthChecks-UI__HealthChecks__4__Name
      key: name__ordering__hc
    - name: HealthChecks-UI__HealthChecks__4__Uri
      key: internalurls__ordering__hc
    - name: HealthChecks-UI__HealthChecks__5__Name
      key: name__basket__hc
    - name: HealthChecks-UI__HealthChecks__5__Uri
      key: internalurls__basket__hc
    - name: HealthChecks-UI__HealthChecks__6__Name
      key: name__catalog__hc
    - name: HealthChecks-UI__HealthChecks__6__Uri
      key: internalurls__catalog__hc
    - name: HealthChecks-UI__HealthChecks__7__Name
      key: name__identity__hc
    - name: HealthChecks-UI__HealthChecks__7__Uri
      key: internalurls__identity__hc
    - name: HealthChecks-UI__HealthChecks__8__Name
      key: name__payment__hc
    - name: HealthChecks-UI__HealthChecks__8__Uri
      key: internalurls__payment__hc
    - name: HealthChecks-UI__HealthChecks__9__Name
      key: name__signalrhub__hc
    - name: HealthChecks-UI__HealthChecks__9__Uri
      key: internalurls__signalrhub__hc
    - name: HealthChecks-UI__HealthChecks__10__Name
      key: name__orderingbackground__hc
    - name: HealthChecks-UI__HealthChecks__10__Uri
      key: internalurls__orderingbackground__hc
    - name: Serilog__SeqServerUrl
      key: all__Serilog__SeqServerUrl
    - name: Serilog__LogstashgUrl
      key:  all__Serilog__LogstashgUrl
    - name: Serilog__LokiUrl
      key:  all__Serilog__LokiUrl
    - name: UseAWS
      key: all__UseAWS
    - name: UseVault
      key: all__UseVault
    - name: OtlpEndpoint
      key: all__OtlpEndpoint
    - name: LocalStack__UseLocalStack
      key: all__LocalStack__UseLocalStack
    - name: LocalStack__LocalStackUrl
      key: all__LocalStack__LocalStackUrl
    - name: AWS__Profile
      key: all__AWS__Profile
    - name: AWS__Region
      key: all__AWS__Region

      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: OrchestratorType
      value: 'K8S'
    - name:  Vault__SecretGroups
      value: EshopWebStatus
