apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Jaeger
    orgId: 1

datasources:
  
  - name: Prometheus
    type: prometheus
    orgId: 1
    uid: my_prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
      
  - name: Loki
    type: loki
    orgId: 1
    uid: my_loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: traceID
          matcherRegex: '"traceID":"(\w+)"'
          url: $${__value.raw}
          datasourceUid: my_jaeger
      
  - name: Jaeger
    type: jaeger
    orgId: 1
    uid: my_jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: my_loki
        filterByTraceID: true
        tags:
          - service