apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    access: proxy
    uid: P8E80F9AEF21F6940
    url: http://loki:3100

  - name: Jaeger
    type: jaeger
    orgId: 1
    # uid: my_jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    # jsonData:
    #   tracesToLogs:
    #     datasourceUid: my_loki
    #     filterByTraceID: true
    #     tags:
    #       - service
