global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'eshop'
    scheme: http
    metrics_path: /metrics
    # metrics_path defaults to '/metrics'
    static_configs:
    # replace the IP with your local IP for development
    # localhost is not it, as that is w/in the container :)
     - targets:
        - basket-api:5103
        - catalog-api:5101
        - identity-api:5105
        - locations-api:5109
        - marketing-api:5110
        - ordering-api:5102
        - ordering-backgroundtasks:5111
        - ordering-signalrhub:5112
        - payment-api:5108
        - webmvc:5100
        - webshoppingagg:5121
        - webspa:5104
        - webstatus:5107
        - webhooks-api:5113
        - webhooks-client:5114

  - job_name: "aggregated-trace-metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger:14269

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]