global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'eshop'
    scheme: http
    metrics_path: /metrics
    # metrics_path defaults to '/metrics'
    static_configs:
    # replace the IP with your local IP for development
    # localhost is not it, as that is w/in the container :)
    - targets:
        - basket-api.default.svc.cluster.local:80
        - catalog-api.default.svc.cluster.local:80
        - identity-api.default.svc.cluster.local:80
        - locations-api.default.svc.cluster.local:80
        - marketing-api.default.svc.cluster.local:80
        - mobileshoppingagg.default.svc.cluster.local:80
        - ordering-api.default.svc.cluster.local:80
        - ordering-backgroundtasks.default.svc.cluster.local:80
        - ordering-signalrhub.default.svc.cluster.local:80
        - payment-api.default.svc.cluster.local:80
        - webmvc.default.svc.cluster.local:80
        - webshoppingagg.default.svc.cluster.local:80
        - webspa.default.svc.cluster.local:80
        - webstatus.default.svc.cluster.local:80
        - webhooks-api.default.svc.cluster.local:80
        - webhooks-web.default.svc.cluster.local:80

  - job_name: "aggregated-trace-metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector.default.svc.cluster.local:8889"]

  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger.default.svc.cluster.local:14269

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]