{{- $name := include "webhooks-web.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $webhooksweb := include "url-of" (list .Values.app.ingress.entries.webhooksweb .) -}}
{{- $webhooks := include "url-of" (list .Values.app.ingress.entries.webhooks .) -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webhooks-web.name" . }}
    chart: {{ template "webhooks-web.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  urls__webhooks: {{ $protocol }}://{{ $webhooks }}
  identity_e: {{ $protocol }}://{{ $identity }}
  webhooksweb_e: {{ $protocol }}://{{ $webhooksweb }}
  urls_webhooksweb: http://{{ .Values.app.svc.webhooksweb }}
  all__Serilog__SeqServerUrl:  {{ .Values.inf.serilog.seqServerUrl }}
  all__Serilog__LogstashgUrl:  {{ .Values.inf.serilog.logstashgUrl }}
  all__Serilog__LokiUrl:  {{ .Values.inf.serilog.lokiUrl }}
  all__Jaeger__Host: {{ .Values.inf.jaeger.host }}
  all__Jaeger__Port: "{{ .Values.inf.jaeger.port }}"
  all__UseAWS: "{{ .Values.inf.useAWS }}"
  all__UseVault: "{{ .Values.inf.useVault }}"
  all__OtlpEndpoint: {{ .Values.inf.otlpEndpoint }}
  all__LocalStack__UseLocalStack: "{{ .Values.inf.localstack.useLocalStack }}"
  all__LocalStack__LocalStackUrl: {{ .Values.inf.localstack.localStackUrl }}
  all__AWS__Profile: {{ .Values.inf.aws.profile }}
  all__AWS__Region: {{ .Values.inf.aws.region }}
