receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:

  logging:
    loglevel: info

  awsxray:
    region: eu-central-1

  awsemf:
    region: eu-central-1

service:
  pipelines:

    # receive traces from Open Telemetry Protocol endpoint
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - awsxray
    
    # receive metrics from Open Telemetry Protocol endpoint
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
        - awsemf
