receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  
  exporters:
  
    logging:
      loglevel: info
  
    awsxray:
      region: eu-central-1
  
    awsemf:
      region: eu-central-1
  
    prometheus:
      endpoint: "0.0.0.0:8889"
  
    otlp:
      endpoint: otel-collector:4317
      tls:
        insecure: true
  
  processors:
    batch:
  
  service:
    pipelines:
      # receive traces from Open Telemetry Protocol endpoint
      traces:
        receivers:
          - otlp
        exporters:
          - logging
          - awsxray
          - otlp   
      # receive metrics from Open Telemetry Protocol endpoint
      metrics:
        receivers:
          - otlp
        processors: 
          - batch
        exporters:
          - logging
          - awsemf
          - prometheus
  