replicaCount: 1
clusterName: eshop-eks
pathBase: /identity
serviceAccountName: eshop-eks-sa

image:
  repository: eshop/identity.api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  class: aws-alb
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  # annotations: 
  #   alb.ingress.kubernetes.io/group.order: "10"
  #   alb.ingress.kubernetes.io/target-type: 'instance'
  #   alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30" # in seconds
  #   alb.ingress.kubernetes.io/healthcheck-path: /healhtz
  #   alb.ingress.kubernetes.io/healty-threshold-count: "1"
  #   # by default, it will create a listener rule on port 80
  #   # you can specify both ports as well like this: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  #   alb.ingress.kubernetes.io/scheme: internet-facing
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

env:
  urls:
  configmap:
    - name: ConnectionString
      key: identity__ConnectionString
    - name: DPConnectionString
      key: identity__keystore
    - name: MvcClient
      key: mvc_e
    - name: SpaClient
      key: spa_e
    - name: BasketApiClient
      key: basket_e
    - name: OrderingApiClient
      key: ordering_e
    - name: MobileShoppingAggClient
      key: mobileshoppingagg_e
    - name: WebShoppingAggClient
      key: webshoppingagg_e
    - name: XamarinCallback
      key: xamarin_callback_e
    - name: WebhooksApiClient
      key: webhooksapi_e
    - name: WebhooksWebClient
      key: webhooksweb_e
    - name: Serilog__SeqServerUrl
      key: all__Serilog__SeqServerUrl
    - name: Serilog__LogstashgUrl
      key:  all__Serilog__LogstashgUrl
    - name: Serilog__LokiUrl
      key:  all__Serilog__LokiUrl
    - name: UseAWS
      key: all__UseAWS
    - name: UseVault
      key: all__UseVault
    - name: OtlpEndpoint
      key: all__OtlpEndpoint
    - name: LocalStack__UseLocalStack
      key: all__LocalStack__UseLocalStack
    - name: LocalStack__LocalStackUrl
      key: all__LocalStack__LocalStackUrl
    - name: AWS__Profile
      key: all__AWS__Profile
    - name: AWS__Region
      key: all__AWS__Region
  values:
    - name: TokenLifetimeMinutes
      value: 120
    - name: PermanentTokenLifetimeDays
      value: 365
    - name: UseCustomizationData
      value: false
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
    - name:  Vault__SecretGroups
      value: EshopIdentityApi
probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80

enableDevspaces: "false"