{{- $name := include "identity-api.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}
{{- $mvc_url := include "url-of" (list .Values.app.ingress.entries.mvc  .) -}}
{{- $spa_url := include "url-of" (list .Values.app.ingress.entries.spa .) -}}
{{- $basket_url := include "url-of" (list .Values.app.ingress.entries.basket .) -}}
{{- $ordering_url := include "url-of" (list .Values.app.ingress.entries.ordering .) -}}
{{- $mobileshoppingagg := include "url-of" (list .Values.app.ingress.entries.mobileshoppingagg .) -}}
{{- $webhoppingagg := include "url-of" (list .Values.app.ingress.entries.webshoppingagg .) -}}
{{- $xamarincallback := include "url-of" (list "xamarincallback" .) -}}
{{- $webhooks_url := include "url-of" (list .Values.app.ingress.entries.webhooks .) -}}
{{- $webhooksweb_url := include "url-of" (list .Values.app.ingress.entries.webhooksweb .) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "identity-api.name" . }}
    chart: {{ template "identity-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  identity__ConnectionString: Server={{ $sqlsrv }};Initial Catalog={{ .Values.inf.sql.identity.db }};User Id={{ .Values.inf.sql.common.user }};Password={{ .Values.inf.sql.common.pwd }};
  identity__keystore: {{ .Values.inf.redis.keystore.constr }}
  mvc_e: http://{{ $mvc_url }}
  spa_e: http://{{ $spa_url }}
  basket_e: http://{{ $basket_url }}
  ordering_e: http://{{ $ordering_url }}
  mobileshoppingagg_e: http://{{ $mobileshoppingagg }}
  webshoppingagg_e: http://{{ $webhoppingagg }}
  xamarin_callback_e: http://{{ $xamarincallback }}
  webhooksapi_e:  http://{{ $webhooks_url }}
  webhooksweb_e: http://{{ $webhooksweb_url }}
  all__Serilog__SeqServerUrl:  {{ .Values.inf.serilog.seqServerUrl }}
  all__Serilog__LogstashgUrl:  {{ .Values.inf.serilog.logstashgUrl }}
  all__Serilog__LokiUrl:  {{ .Values.inf.serilog.lokiUrl }}
  all__Jaeger__Host: {{ .Values.inf.jaeger.host }}
  all__Jaeger__Port: {{ .Values.inf.jaeger.port }}
  all__UseAWS: {{ .Values.inf.useAWS }}
  all__UseVault: {{ .Values.inf.useVault }}
  all__OtlpEndpoint: {{ .Values.inf.otlpEndpoint }}
  all__LocalStack__UseLocalStack: {{ .Values.inf.localstack.useLocalStack }}
  all__LocalStack__LocalStackUrl: {{ .Values.inf.localstack.localStackUrl }}
  all__AWS__Profile: {{ .Values.inf.aws.profile }}
  all__AWS__Region: {{ .Values.inf.aws.region }}