replicaCount: 1
clusterName: eshop-eks
pathBase: /webhooks-web
serviceAccountName: eshop-eks-sa

image:
  repository: eshop/webhooks.client
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  class: nginx
  annotations: {}
  hosts:
    - chart-example.local
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: WebhooksUrl
      key: urls__webhooks
    - name: IdentityUrl
      key: identity_e
    - name: CallbackUrl
      key: webhooksweb_e
    - name: SelfUrl
      key: webhooksweb_e
    - name: Serilog__SeqServerUrl
      key: all__Serilog__SeqServerUrl
    - name: Serilog__LogstashgUrl
      key:  all__Serilog__LogstashgUrl
    - name: Serilog__LokiUrl
      key:  all__Serilog__LokiUrl
    - name: UseAWS
      key: all__UseAWS
    - name: UseVault
      key: all__UseVault
    - name: OtlpEndpoint
      key: all__OtlpEndpoint
    - name: LocalStack__UseLocalStack
      key: all__LocalStack__UseLocalStack
    - name: LocalStack__LocalStackUrl
      key: all__LocalStack__LocalStackUrl
    - name: AWS__Profile
      key: all__AWS__Profile
    - name: AWS__Region
      key: all__AWS__Region
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: OrchestratorType
      value: 'K8S'
    - name: Token
      value: "WebHooks-Demo-Web"       # Can use whatever you want


