{{- $name := include "webshoppingagg.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webshoppingagg.name" . }}
    chart: {{ template "webshoppingagg.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  webshoppingagg__keystore: {{ .Values.inf.redis.keystore.constr }}
  internalurls__basket: http://{{ .Values.app.svc.basket }}
  internalurls__catalog: http://{{ .Values.app.svc.catalog }}
  internalurls__identity: http://{{ .Values.app.svc.identity }}
  internalurls__ordering: http://{{ .Values.app.svc.ordering }}
  internalurls__basket__hc: http://{{ .Values.app.svc.basket }}/hc
  internalurls__catalog__hc: http://{{ .Values.app.svc.catalog }}/hc
  internalurls__identity__hc: http://{{ .Values.app.svc.identity }}/hc
  internalurls__ordering__hc: http://{{ .Values.app.svc.ordering }}/hc
  internalurls__payment__hc: http://{{ .Values.app.svc.payment }}/hc
  internalurls__grpcBasket: "http://{{ .Values.app.svc.basket }}:{{ .Values.service.grpcPort }}"
  internalurls__grpcCatalog: "http://{{ .Values.app.svc.catalog }}:{{ .Values.service.grpcPort }}"
  internalurls__grpcOrdering: "http://{{ .Values.app.svc.ordering }}:{{ .Values.service.grpcPort }}"
  urls__IdentityUrlExternal: {{ $protocol }}://{{ $identity }}
  all__Serilog__SeqServerUrl:  {{ .Values.inf.serilog.seqServerUrl }}
  all__Serilog__LogstashgUrl:  {{ .Values.inf.serilog.logstashgUrl }}
  all__Serilog__LokiUrl:  {{ .Values.inf.serilog.lokiUrl }}
  all__UseAWS: "{{ .Values.inf.useAWS }}"
  all__UseVault: "{{ .Values.inf.useVault }}"
  all__OtlpEndpoint: {{ .Values.inf.otlpEndpoint }}
  all__LocalStack__UseLocalStack: "{{ .Values.inf.localstack.useLocalStack }}"
  all__LocalStack__LocalStackUrl: {{ .Values.inf.localstack.localStackUrl }}
  all__AWS__Profile: {{ .Values.inf.aws.profile }}
  all__AWS__Region: {{ .Values.inf.aws.region }}
