{{- $name := include "marketing-api.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $webshoppingapigw := include "url-of" (list .Values.app.ingress.entries.webshoppingapigw .) -}}
{{- $mongo := include "mongo-name" . -}}
{{- $sqlsrv := include "sql-name" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "marketing-api.name" . }}
    chart: {{ template "marketing-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  internalurls__IdentityUrl: http://{{ .Values.app.svc.identity }}
  urls__IdentityUrl: {{ $protocol }}://{{ $identity }}
  marketing__ConnectionString: Server={{ $sqlsrv }};Initial Catalog={{ .Values.inf.sql.marketing.db }};User Id={{ .Values.inf.sql.common.user }};Password={{ .Values.inf.sql.common.pwd }};TrustServerCertificate=True;
  marketing__MongoConnectionString: mongodb://{{ $mongo }}
  marketing__MongoDatabase: {{ .Values.inf.mongo.marketing.database }} 
  marketing__PicBaseUrl: {{ $protocol }}://{{ $webshoppingapigw }}/c/api/v1/catalog/items/[0]/pic/
  all__Serilog__SeqServerUrl:  {{ .Values.inf.serilog.seqServerUrl }}
  all__Serilog__LogstashgUrl:  {{ .Values.inf.serilog.logstashgUrl }}
  all__Serilog__LokiUrl:  {{ .Values.inf.serilog.lokiUrl }}
  all__EventBus__Host: {{ .Values.inf.eventbus.host }}
  all__EventBus__UserName: {{ .Values.inf.eventbus.username }}
  all__EventBus__Password: {{ .Values.inf.eventbus.password }}
  all__EventBus__IsSecure: "{{ .Values.inf.eventbus.isSecure }}"
  all__EventBus__PersistenceEnabled: "{{ .Values.inf.eventbus.persistenceEnabled }}"
  all__EventBus__OutboxEnabled: "{{ .Values.inf.eventbus.outboxEnabled }}"
  all__EventBus__RabbitMQEnabled: "{{ .Values.inf.eventbus.rabbitmqEnabled }}"
  all__EventBus__RetryCount: "{{ .Values.inf.eventbus.retryCount }}"
  all__EventBus__AuditEnabled: "{{ .Values.inf.eventbus.auditEnabled }}"
  all__EventBus__FleetManager__Enabled: "{{ .Values.inf.eventbus.fleetManager.enabled }}"
  all__EventBus__FleetManager__Url: {{ .Values.inf.eventbus.fleetManager.url }}
  all__EventBus__FleetManager__ApiKey: {{ .Values.inf.eventbus.fleetManager.apiKey }}
  all__S3Enabled: "{{ .Values.inf.S3Enabled }}"
  all__UseAWS: "{{ .Values.inf.useAWS }}"
  all__UseDocumentDb: "{{ .Values.inf.useDocumentDb }}"
  all__UseVault: "{{ .Values.inf.useVault }}"
  all__OtlpEndpoint: {{ .Values.inf.otlpEndpoint }}
  all__LocalStack__UseLocalStack: "{{ .Values.inf.localstack.useLocalStack }}"
  all__LocalStack__LocalStackUrl: {{ .Values.inf.localstack.localStackUrl }}
  all__AWS__Profile: {{ .Values.inf.aws.profile }}
  all__AWS__Region: {{ .Values.inf.aws.region }}