replicaCount: 1
clusterName: eshop-eks
pathBase: /mobileshoppingapigw

image:
  repository: envoyproxy/envoy
  tag: v1.21.0

service:
  type: NodePort
  port: 80
  adminPort: 8001  

ingress:
  enabled: true
  class: aws-alb
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   nginx.ingress.kubernetes.io/use-regex: "true"
  # annotations: 
  #   alb.ingress.kubernetes.io/group.order: "10"
  #   alb.ingress.kubernetes.io/target-type: 'instance'
  #   alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30" # in seconds
  #   alb.ingress.kubernetes.io/healthcheck-path: /healhtz
  #   alb.ingress.kubernetes.io/healty-threshold-count: "1"
  #   # by default, it will create a listener rule on port 80
  #   # you can specify both ports as well like this: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #   alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
  #   alb.ingress.kubernetes.io/scheme: internet-facing
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

env: {}

envoy:
  configPath: /etc/envoy

probes:
  liveness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 15
    port: 8001
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 60
    port: 8001